(define-package "foundation-pack" "1.0-BETA-23"
  "Emacs Live pack providing the foundation stone on top of which all packs are built. Sets the visual theme."
  '((auto-compile "1.0.10")
    (buffer-move "0.4")
    (dash "2.2.0")
    (elisp-slime-nav "0")
    (exec-path-from-shell "0")
    (find-file-in-project "3.2")
    (flx "0.1")
    (idomenu "0")
    (key-chord "0.5")
    (pkg-info "0.2-cvs")
    (popwin "0.7.0alpha")
    (smex "2.1")
    (smooth-scrolling "1.10")
    (win-switch "1.0.6")
    (window-number "0")))
